### PR TITLE
fix exercice 6 solution link

### PR DESCRIPTION
**Pull request by JohannCarfantan**
## 📝 What is this PR

Following [this support ticket](https://phantombuster.zendesk.com/agent/tickets/81806) it appears that there's a typo in the link.

### CODE REVIEW

**Review by arnauddrain — APPROVED** [review]
LGTM
@paps @stressGC do you know how this is deployed?

**Comment by stressGC** [comment]
I think that @paps used to deploy it manually. It is really legacy.

You should ping him on Slack I don't think that he'll see the GH notifs

**Review by stressGC — APPROVED** [review]

**Comment by paps** [comment]
Hello :) Thanks for the PR. We have a mini heroku app hosting this, merging to master should do the trick, let's see

**Comment by paps** [comment]
Ok it was more complicated than that, but it's deployed now. All good, thanks

**Pull request merged**
